version: '3.7'

services:
  wep-app:
    container_name: simple-react-redux-wep-app:latest
    ports:
     - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile.prod
    stdin_open: true
    tty: true
    environment:
      - PORT=3000
      - PUBLIC_URL=${ROUTE_URL}
    env_file:
      ./.env
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test.rule=PathPrefix(`/${ROUTE_URL}`) || PathPrefix(`/${ROUTE_URL}/`)"
      - "traefik.http.routers.test.entrypoints=web"
      - "traefik.http.routers.test.middlewares=test-final"
      - "traefik.http.middlewares.test-final.stripprefix.prefixes=${ROUTE_URL},/${ROUTE_URL}"
      - "traefik.http.middlewares.test-final.stripprefix.forceslash=true"


networks:
  web: 
    external: true 
